# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# PLEASE REMOVE ALL GENERATED COMMENTS WHEN SUBMITTING YOUR PULL REQUEST!

class IbBoxSpread < Formula
  desc "Automated options arbitrage trading system for Interactive Brokers using box spread strategies"
  homepage "https://github.com/davidl71/ib_box_spread_full_universal"
  # For private repositories, use GitDownloadStrategy with SSH URL
  # This allows Homebrew to clone the repo and checkout the tag
  url "git@github.com:davidl71/ib_box_spread_full_universal.git", tag: "v1.0.0", using: :git
  license "MIT"
  head "git@github.com:davidl71/ib_box_spread_full_universal.git", branch: "main", using: :git

  depends_on "cmake" => :build
  depends_on "ninja" => :build
  depends_on "pkg-config" => :build
  depends_on "protobuf" => :build
  depends_on "abseil" => :build

  # Optional dependencies for full functionality
  depends_on "go" => :optional
  depends_on "python@3.11" => :optional

  def install
    # Build main C++ binary
    system "cmake", "-S", "native", "-B", "build",
           "-DCMAKE_BUILD_TYPE=Release",
           "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
           *std_cmake_args
    system "cmake", "--build", "build", "--config", "Release"

    # Install main binary
    bin.install "build/bin/ib_box_spread"

    # Install man page if it exists
    man1.install "docs/man/ib_box_spread.1" if File.exist?("docs/man/ib_box_spread.1")

    # Install configuration example
    pkgshare.install "config/config.example.json"
  end

  test do
    # Test that binary exists
    assert_predicate bin/"ib_box_spread", :exist?

    # Test that binary runs (may fail without config, but should not crash)
    system bin/"ib_box_spread", "--help", :status => false
  end
end
