# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# PLEASE REMOVE ALL GENERATED COMMENTS WHEN SUBMITTING YOUR PULL REQUEST!

class IbBoxSpreadTui < Formula
  desc "Terminal User Interface for IBKR Box Spread trading system"
  homepage "https://github.com/davidl71/ib_box_spread_full_universal"
  # For private repositories, use GitDownloadStrategy with SSH URL
  # This allows Homebrew to clone the repo and checkout the tag
  url "git@github.com:davidl71/ib_box_spread_full_universal.git", tag: "v1.0.0", using: :git
  license "MIT"
  head "git@github.com:davidl71/ib_box_spread_full_universal.git", branch: "main", using: :git

  depends_on "cmake" => :build
  depends_on "ftxui" => :build

  def install
    # Build C++ TUI using CMake
    mkdir "build" do
      system "cmake", "..", "-DENABLE_TUI=ON", *std_cmake_args
      system "cmake", "--build", "."
      system "cmake", "--install", ".", "--component", "tui"
    end

    # Install binary (CMake installs to bin/ib_box_spread_tui)
    # Create symlink for compatibility with old name
    bin.install_symlink "ib_box_spread_tui" => "ib-box-spread-tui"
  end

  test do
    # Test that binary exists and can be executed
    assert_predicate bin/"ib_box_spread_tui", :exist?
    system bin/"ib_box_spread_tui", "--help" rescue nil  # May not have --help flag yet
  end
end
