# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# PLEASE REMOVE ALL GENERATED COMMENTS WHEN SUBMITTING YOUR PULL REQUEST!

class IbBoxSpreadTui < Formula
  desc "Terminal User Interface for IBKR Box Spread trading system"
  homepage "https://github.com/davidl71/ib_box_spread_full_universal"
  # For private repositories, use GitDownloadStrategy with SSH URL
  # This allows Homebrew to clone the repo and checkout the tag
  url "git@github.com:davidl71/ib_box_spread_full_universal.git", tag: "v1.0.0", using: :git
  license "MIT"
  head "git@github.com:davidl71/ib_box_spread_full_universal.git", branch: "main", using: :git

  depends_on "go" => :build

  def install
    # Build TUI binary
    system "go", "build", "-ldflags", "-s -w",
           "-o", "ib-box-spread-tui",
           "./tui/cmd/tui"

    # Install binary
    bin.install "ib-box-spread-tui"

    # Install man page
    man1.install "tui/man/ib-box-spread-tui.1"
  end

  test do
    # Test that binary exists and can be executed
    assert_predicate bin/"ib-box-spread-tui", :exist?

    # Test man page exists
    assert_predicate man1/"ib-box-spread-tui.1", :exist?
  end
end
