"""
cash_flow_portfolio_manager.py - Cash flow-aware portfolio allocation and cash management

Integrates cash flow forecasting with portfolio decisions:
- Maintains minimum cash reserves for upcoming obligations
- Generates alerts when liquidity is insufficient
- Recommends allocation adjustments based on projected cash flows
- Ensures sufficient liquidity for loan payments and maturities
"""

from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Dict, List, Optional

from .cash_flow_timeline import (
    calculate_cash_flow_timeline,
    CashFlowTimelineResult,
)

logger = logging.getLogger(__name__)


class AlertSeverity(Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AllocationAction(Enum):
    HOLD = "hold"
    REDUCE_EXPOSURE = "reduce_exposure"
    INCREASE_RESERVES = "increase_reserves"
    DEPLOY_EXCESS = "deploy_excess"
    REBALANCE = "rebalance"


@dataclass
class CashReservePolicy:
    """Policy defining minimum cash reserves relative to upcoming obligations."""
    min_months_coverage: int = 3
    min_reserve_usd: float = 10000.0
    reserve_multiplier: float = 1.2
    alert_threshold_pct: float = 0.80
    critical_threshold_pct: float = 0.50
    max_single_position_pct: float = 0.25


@dataclass
class CashFlowAlert:
    """Alert generated by cash flow monitoring."""
    severity: AlertSeverity
    message: str
    trigger_date: str
    amount: float
    position_name: str
    action_recommended: AllocationAction
    timestamp: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict:
        return {
            "severity": self.severity.value,
            "message": self.message,
            "trigger_date": self.trigger_date,
            "amount": self.amount,
            "position_name": self.position_name,
            "action_recommended": self.action_recommended.value,
            "timestamp": self.timestamp.isoformat(),
        }


@dataclass
class AllocationRecommendation:
    """Recommended portfolio allocation adjustment."""
    action: AllocationAction
    reason: str
    amount_usd: float = 0.0
    target_instrument: str = ""
    urgency_days: int = 0
    confidence: float = 0.0

    def to_dict(self) -> Dict:
        return {
            "action": self.action.value,
            "reason": self.reason,
            "amount_usd": self.amount_usd,
            "target_instrument": self.target_instrument,
            "urgency_days": self.urgency_days,
            "confidence": self.confidence,
        }


@dataclass
class CashManagementSnapshot:
    """Complete cash management analysis."""
    available_cash: float
    required_reserves: float
    reserve_coverage_ratio: float
    upcoming_outflows_30d: float
    upcoming_outflows_90d: float
    upcoming_inflows_30d: float
    upcoming_inflows_90d: float
    net_position_30d: float
    net_position_90d: float
    alerts: List[CashFlowAlert] = field(default_factory=list)
    recommendations: List[AllocationRecommendation] = field(default_factory=list)
    excess_cash: float = 0.0
    deployable_amount: float = 0.0
    generated_time: datetime = field(default_factory=datetime.now)

    def to_dict(self) -> Dict:
        return {
            "available_cash": self.available_cash,
            "required_reserves": self.required_reserves,
            "reserve_coverage_ratio": self.reserve_coverage_ratio,
            "upcoming_outflows_30d": self.upcoming_outflows_30d,
            "upcoming_outflows_90d": self.upcoming_outflows_90d,
            "upcoming_inflows_30d": self.upcoming_inflows_30d,
            "upcoming_inflows_90d": self.upcoming_inflows_90d,
            "net_position_30d": self.net_position_30d,
            "net_position_90d": self.net_position_90d,
            "excess_cash": self.excess_cash,
            "deployable_amount": self.deployable_amount,
            "alerts": [a.to_dict() for a in self.alerts],
            "recommendations": [r.to_dict() for r in self.recommendations],
            "generated_time": self.generated_time.isoformat(),
        }


class CashFlowPortfolioManager:
    """
    Manages portfolio allocation with awareness of upcoming cash flows.

    Monitors scheduled obligations (loan payments, maturities), maintains
    required cash reserves, and generates alerts/recommendations when
    action is needed.
    """

    def __init__(self, policy: Optional[CashReservePolicy] = None):
        self.policy = policy or CashReservePolicy()

    def analyze(
        self,
        positions: List[Dict],
        bank_accounts: List[Dict],
        available_cash: float,
        projection_months: int = 12,
    ) -> CashManagementSnapshot:
        """
        Analyze portfolio cash position against upcoming obligations.

        Args:
            positions: Position dicts (same format as SnapshotPayload.positions)
            bank_accounts: Bank account dicts
            available_cash: Current available cash balance
            projection_months: Months to project forward

        Returns:
            CashManagementSnapshot with alerts and recommendations
        """
        timeline = calculate_cash_flow_timeline(
            positions=positions,
            bank_accounts=bank_accounts,
            projection_months=projection_months,
        )

        now = datetime.now()
        cutoff_30 = (now + timedelta(days=30)).strftime("%Y-%m-%d")
        cutoff_90 = (now + timedelta(days=90)).strftime("%Y-%m-%d")

        outflows_30 = sum(abs(e.amount) for e in timeline.events if e.amount < 0 and e.date <= cutoff_30)
        outflows_90 = sum(abs(e.amount) for e in timeline.events if e.amount < 0 and e.date <= cutoff_90)
        inflows_30 = sum(e.amount for e in timeline.events if e.amount > 0 and e.date <= cutoff_30)
        inflows_90 = sum(e.amount for e in timeline.events if e.amount > 0 and e.date <= cutoff_90)

        reserve_months = self.policy.min_months_coverage
        monthly_avg_outflow = outflows_90 / 3.0 if outflows_90 > 0 else 0.0
        required_reserves = max(
            self.policy.min_reserve_usd,
            monthly_avg_outflow * reserve_months * self.policy.reserve_multiplier,
        )

        coverage = available_cash / required_reserves if required_reserves > 0 else float("inf")
        excess = max(0.0, available_cash - required_reserves)
        deployable = excess * 0.80

        alerts = self._generate_alerts(timeline, available_cash, required_reserves, coverage)
        recommendations = self._generate_recommendations(
            available_cash, required_reserves, excess, deployable, timeline, coverage,
        )

        return CashManagementSnapshot(
            available_cash=available_cash,
            required_reserves=required_reserves,
            reserve_coverage_ratio=coverage,
            upcoming_outflows_30d=outflows_30,
            upcoming_outflows_90d=outflows_90,
            upcoming_inflows_30d=inflows_30,
            upcoming_inflows_90d=inflows_90,
            net_position_30d=inflows_30 - outflows_30,
            net_position_90d=inflows_90 - outflows_90,
            alerts=alerts,
            recommendations=recommendations,
            excess_cash=excess,
            deployable_amount=deployable,
        )

    def _generate_alerts(
        self,
        timeline: CashFlowTimelineResult,
        available_cash: float,
        required_reserves: float,
        coverage: float,
    ) -> List[CashFlowAlert]:
        alerts: List[CashFlowAlert] = []

        if coverage < self.policy.critical_threshold_pct:
            alerts.append(CashFlowAlert(
                severity=AlertSeverity.CRITICAL,
                message=f"Cash reserves critically low: {coverage:.0%} of required {required_reserves:,.0f}",
                trigger_date=datetime.now().strftime("%Y-%m-%d"),
                amount=required_reserves - available_cash,
                position_name="portfolio",
                action_recommended=AllocationAction.INCREASE_RESERVES,
            ))
        elif coverage < self.policy.alert_threshold_pct:
            alerts.append(CashFlowAlert(
                severity=AlertSeverity.WARNING,
                message=f"Cash reserves below target: {coverage:.0%} of required {required_reserves:,.0f}",
                trigger_date=datetime.now().strftime("%Y-%m-%d"),
                amount=required_reserves - available_cash,
                position_name="portfolio",
                action_recommended=AllocationAction.INCREASE_RESERVES,
            ))

        # Large upcoming outflows
        running = available_cash
        for event in sorted(timeline.events, key=lambda e: e.date):
            running += event.amount
            if running < 0 and event.amount < 0:
                alerts.append(CashFlowAlert(
                    severity=AlertSeverity.CRITICAL,
                    message=f"Insufficient funds for {event.description}: shortfall ${abs(running):,.0f}",
                    trigger_date=event.date,
                    amount=event.amount,
                    position_name=event.position_name,
                    action_recommended=AllocationAction.INCREASE_RESERVES,
                ))
            elif running < required_reserves * 0.5 and event.amount < 0:
                alerts.append(CashFlowAlert(
                    severity=AlertSeverity.WARNING,
                    message=f"Reserves will drop to ${running:,.0f} after {event.description}",
                    trigger_date=event.date,
                    amount=event.amount,
                    position_name=event.position_name,
                    action_recommended=AllocationAction.REDUCE_EXPOSURE,
                ))

        return alerts

    def _generate_recommendations(
        self,
        available_cash: float,
        required_reserves: float,
        excess: float,
        deployable: float,
        timeline: CashFlowTimelineResult,
        coverage: float,
    ) -> List[AllocationRecommendation]:
        recs: List[AllocationRecommendation] = []

        if coverage < self.policy.alert_threshold_pct:
            shortfall = required_reserves - available_cash
            recs.append(AllocationRecommendation(
                action=AllocationAction.INCREASE_RESERVES,
                reason=f"Build reserves to cover {self.policy.min_months_coverage} months of obligations",
                amount_usd=shortfall,
                urgency_days=7,
                confidence=0.9,
            ))

        if deployable > 5000:
            recs.append(AllocationRecommendation(
                action=AllocationAction.DEPLOY_EXCESS,
                reason=f"Excess cash available after reserves: ${excess:,.0f}",
                amount_usd=deployable,
                target_instrument="box_spread_or_treasury",
                urgency_days=30,
                confidence=0.7,
            ))

        # Rebalance if large inflow is coming
        now_str = datetime.now().strftime("%Y-%m-%d")
        cutoff_60 = (datetime.now() + timedelta(days=60)).strftime("%Y-%m-%d")
        large_inflows = [
            e for e in timeline.events
            if e.amount > 10000 and now_str <= e.date <= cutoff_60
        ]
        for inflow in large_inflows:
            recs.append(AllocationRecommendation(
                action=AllocationAction.REBALANCE,
                reason=f"Upcoming inflow of ${inflow.amount:,.0f} from {inflow.position_name} on {inflow.date}",
                amount_usd=inflow.amount,
                target_instrument="reinvestment",
                urgency_days=max(1, (datetime.fromisoformat(inflow.date) - datetime.now()).days),
                confidence=0.6,
            ))

        return recs

    def get_rebalance_triggers(
        self,
        positions: List[Dict],
        bank_accounts: List[Dict],
        available_cash: float,
    ) -> List[Dict]:
        """
        Get date-based rebalance triggers for upcoming cash flow events.

        Returns list of trigger dicts with date, amount, and recommended action.
        """
        snapshot = self.analyze(positions, bank_accounts, available_cash)
        triggers = []

        for alert in snapshot.alerts:
            if alert.action_recommended in (AllocationAction.INCREASE_RESERVES, AllocationAction.REDUCE_EXPOSURE):
                triggers.append({
                    "date": alert.trigger_date,
                    "type": "cash_flow_obligation",
                    "amount": alert.amount,
                    "position": alert.position_name,
                    "action": alert.action_recommended.value,
                    "severity": alert.severity.value,
                })

        for rec in snapshot.recommendations:
            if rec.action == AllocationAction.REBALANCE:
                triggers.append({
                    "date": (datetime.now() + timedelta(days=rec.urgency_days)).strftime("%Y-%m-%d"),
                    "type": "reinvestment_opportunity",
                    "amount": rec.amount_usd,
                    "position": rec.target_instrument,
                    "action": "rebalance",
                    "severity": "info",
                })

        triggers.sort(key=lambda t: t["date"])
        return triggers
