#!/usr/bin/env python3
"""Recreate python/generated/__init__.py with re-exports from python.generated.ib.platform.v1.

The directory python/generated/ is gitignored; betterproto writes into it from
./proto/generate.sh. This script writes the hand-maintained __init__.py so that
`from python.generated import StrategySignal, DiscountBankBalance, ...` works.

Run from repo root after ./proto/generate.sh:
  uv run python scripts/recreate_python_generated_init.py
  # or: PYTHONPATH=. python scripts/recreate_python_generated_init.py
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
GENERATED_DIR = REPO_ROOT / "python" / "generated"
INIT_PY = GENERATED_DIR / "__init__.py"


def main() -> int:
    sys.path.insert(0, str(REPO_ROOT))
    try:
        from python.generated.ib.platform import v1
    except ImportError as e:
        print("fatal: could not import python.generated.ib.platform.v1:", e, file=sys.stderr)
        print("Run ./proto/generate.sh first, then run this script from repo root.", file=sys.stderr)
        return 1

    # Collect message/enum types (betterproto generates classes with __betterproto__)
    names = []
    for name in dir(v1):
        if name.startswith("_"):
            continue
        obj = getattr(v1, name)
        if isinstance(obj, type) and getattr(obj, "__module__", "").startswith("python.generated"):
            names.append(name)
    names.sort()

    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    content = f'''# Re-export platform proto types for a single import surface.
# Generated by scripts/recreate_python_generated_init.py (run after ./proto/generate.sh).
# The python/generated/ directory is gitignored; this file must be recreated after codegen.

from python.generated.ib.platform.v1 import (
    {chr(10).join("    " + n + "," for n in names)}
)

__all__ = [
    {chr(10).join('    "' + n + '",' for n in names)}
]
'''
    INIT_PY.write_text(content, encoding="utf-8")
    print("wrote", INIT_PY, "with", len(names), "exports")
    return 0


if __name__ == "__main__":
    sys.exit(main())
