// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: messages.proto

package pbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertLevel int32

const (
	AlertLevel_ALERT_LEVEL_UNSPECIFIED AlertLevel = 0
	AlertLevel_ALERT_LEVEL_INFO        AlertLevel = 1
	AlertLevel_ALERT_LEVEL_WARNING     AlertLevel = 2
	AlertLevel_ALERT_LEVEL_ERROR       AlertLevel = 3
)

// Enum value maps for AlertLevel.
var (
	AlertLevel_name = map[int32]string{
		0: "ALERT_LEVEL_UNSPECIFIED",
		1: "ALERT_LEVEL_INFO",
		2: "ALERT_LEVEL_WARNING",
		3: "ALERT_LEVEL_ERROR",
	}
	AlertLevel_value = map[string]int32{
		"ALERT_LEVEL_UNSPECIFIED": 0,
		"ALERT_LEVEL_INFO":        1,
		"ALERT_LEVEL_WARNING":     2,
		"ALERT_LEVEL_ERROR":       3,
	}
)

func (x AlertLevel) Enum() *AlertLevel {
	p := new(AlertLevel)
	*p = x
	return p
}

func (x AlertLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AlertLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (AlertLevel) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x AlertLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AlertLevel.Descriptor instead.
func (AlertLevel) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

type OptionTypeEnum int32

const (
	OptionTypeEnum_OPTION_TYPE_UNSPECIFIED OptionTypeEnum = 0
	OptionTypeEnum_OPTION_TYPE_CALL        OptionTypeEnum = 1
	OptionTypeEnum_OPTION_TYPE_PUT         OptionTypeEnum = 2
)

// Enum value maps for OptionTypeEnum.
var (
	OptionTypeEnum_name = map[int32]string{
		0: "OPTION_TYPE_UNSPECIFIED",
		1: "OPTION_TYPE_CALL",
		2: "OPTION_TYPE_PUT",
	}
	OptionTypeEnum_value = map[string]int32{
		"OPTION_TYPE_UNSPECIFIED": 0,
		"OPTION_TYPE_CALL":        1,
		"OPTION_TYPE_PUT":         2,
	}
)

func (x OptionTypeEnum) Enum() *OptionTypeEnum {
	p := new(OptionTypeEnum)
	*p = x
	return p
}

func (x OptionTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OptionTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[1].Descriptor()
}

func (OptionTypeEnum) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[1]
}

func (x OptionTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OptionTypeEnum.Descriptor instead.
func (OptionTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

type MarketDataEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid           float64                `protobuf:"fixed64,2,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           float64                `protobuf:"fixed64,3,opt,name=ask,proto3" json:"ask,omitempty"`
	Last          float64                `protobuf:"fixed64,4,opt,name=last,proto3" json:"last,omitempty"`
	Volume        uint64                 `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketDataEvent) Reset() {
	*x = MarketDataEvent{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketDataEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketDataEvent) ProtoMessage() {}

func (x *MarketDataEvent) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketDataEvent.ProtoReflect.Descriptor instead.
func (*MarketDataEvent) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *MarketDataEvent) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MarketDataEvent) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *MarketDataEvent) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *MarketDataEvent) GetLast() float64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *MarketDataEvent) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MarketDataEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type CandleSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float64                `protobuf:"fixed64,1,opt,name=open,proto3" json:"open,omitempty"`
	High          float64                `protobuf:"fixed64,2,opt,name=high,proto3" json:"high,omitempty"`
	Low           float64                `protobuf:"fixed64,3,opt,name=low,proto3" json:"low,omitempty"`
	Close         float64                `protobuf:"fixed64,4,opt,name=close,proto3" json:"close,omitempty"`
	Volume        uint64                 `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Entry         float64                `protobuf:"fixed64,6,opt,name=entry,proto3" json:"entry,omitempty"`
	Updated       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated,proto3" json:"updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandleSnapshot) Reset() {
	*x = CandleSnapshot{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandleSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandleSnapshot) ProtoMessage() {}

func (x *CandleSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandleSnapshot.ProtoReflect.Descriptor instead.
func (*CandleSnapshot) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CandleSnapshot) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *CandleSnapshot) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *CandleSnapshot) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *CandleSnapshot) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *CandleSnapshot) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CandleSnapshot) GetEntry() float64 {
	if x != nil {
		return x.Entry
	}
	return 0
}

func (x *CandleSnapshot) GetUpdated() *timestamppb.Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

type SymbolSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Last          float64                `protobuf:"fixed64,2,opt,name=last,proto3" json:"last,omitempty"`
	Bid           float64                `protobuf:"fixed64,3,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask           float64                `protobuf:"fixed64,4,opt,name=ask,proto3" json:"ask,omitempty"`
	Spread        float64                `protobuf:"fixed64,5,opt,name=spread,proto3" json:"spread,omitempty"`
	Roi           float64                `protobuf:"fixed64,6,opt,name=roi,proto3" json:"roi,omitempty"`
	MakerCount    uint32                 `protobuf:"varint,7,opt,name=maker_count,json=makerCount,proto3" json:"maker_count,omitempty"`
	TakerCount    uint32                 `protobuf:"varint,8,opt,name=taker_count,json=takerCount,proto3" json:"taker_count,omitempty"`
	Volume        uint64                 `protobuf:"varint,9,opt,name=volume,proto3" json:"volume,omitempty"`
	Candle        *CandleSnapshot        `protobuf:"bytes,10,opt,name=candle,proto3" json:"candle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolSnapshot) Reset() {
	*x = SymbolSnapshot{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolSnapshot) ProtoMessage() {}

func (x *SymbolSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolSnapshot.ProtoReflect.Descriptor instead.
func (*SymbolSnapshot) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *SymbolSnapshot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SymbolSnapshot) GetLast() float64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *SymbolSnapshot) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *SymbolSnapshot) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *SymbolSnapshot) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

func (x *SymbolSnapshot) GetRoi() float64 {
	if x != nil {
		return x.Roi
	}
	return 0
}

func (x *SymbolSnapshot) GetMakerCount() uint32 {
	if x != nil {
		return x.MakerCount
	}
	return 0
}

func (x *SymbolSnapshot) GetTakerCount() uint32 {
	if x != nil {
		return x.TakerCount
	}
	return 0
}

func (x *SymbolSnapshot) GetVolume() uint64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *SymbolSnapshot) GetCandle() *CandleSnapshot {
	if x != nil {
		return x.Candle
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	CostBasis     float64                `protobuf:"fixed64,4,opt,name=cost_basis,json=costBasis,proto3" json:"cost_basis,omitempty"`
	Mark          float64                `protobuf:"fixed64,5,opt,name=mark,proto3" json:"mark,omitempty"`
	UnrealizedPnl float64                `protobuf:"fixed64,6,opt,name=unrealized_pnl,json=unrealizedPnl,proto3" json:"unrealized_pnl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Position) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Position) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Position) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Position) GetCostBasis() float64 {
	if x != nil {
		return x.CostBasis
	}
	return 0
}

func (x *Position) GetMark() float64 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *Position) GetUnrealizedPnl() float64 {
	if x != nil {
		return x.UnrealizedPnl
	}
	return 0
}

type HistoricPosition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	RealizedPnl   float64                `protobuf:"fixed64,4,opt,name=realized_pnl,json=realizedPnl,proto3" json:"realized_pnl,omitempty"`
	ClosedAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoricPosition) Reset() {
	*x = HistoricPosition{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoricPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoricPosition) ProtoMessage() {}

func (x *HistoricPosition) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoricPosition.ProtoReflect.Descriptor instead.
func (*HistoricPosition) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *HistoricPosition) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoricPosition) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HistoricPosition) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *HistoricPosition) GetRealizedPnl() float64 {
	if x != nil {
		return x.RealizedPnl
	}
	return 0
}

func (x *HistoricPosition) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Side          string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	SubmittedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=submitted_at,json=submittedAt,proto3" json:"submitted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Order) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *Order) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Order) GetSubmittedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SubmittedAt
	}
	return nil
}

type StrategyDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Side          string                 `protobuf:"bytes,3,opt,name=side,proto3" json:"side,omitempty"`
	Mark          float64                `protobuf:"fixed64,4,opt,name=mark,proto3" json:"mark,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategyDecision) Reset() {
	*x = StrategyDecision{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategyDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyDecision) ProtoMessage() {}

func (x *StrategyDecision) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyDecision.ProtoReflect.Descriptor instead.
func (*StrategyDecision) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *StrategyDecision) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StrategyDecision) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StrategyDecision) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *StrategyDecision) GetMark() float64 {
	if x != nil {
		return x.Mark
	}
	return 0
}

func (x *StrategyDecision) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type StrategySignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StrategySignal) Reset() {
	*x = StrategySignal{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StrategySignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategySignal) ProtoMessage() {}

func (x *StrategySignal) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategySignal.ProtoReflect.Descriptor instead.
func (*StrategySignal) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *StrategySignal) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *StrategySignal) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *StrategySignal) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type RiskStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskStatus) Reset() {
	*x = RiskStatus{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskStatus) ProtoMessage() {}

func (x *RiskStatus) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskStatus.ProtoReflect.Descriptor instead.
func (*RiskStatus) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *RiskStatus) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *RiskStatus) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RiskStatus) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RiskLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	MaxPosition   int32                  `protobuf:"varint,2,opt,name=max_position,json=maxPosition,proto3" json:"max_position,omitempty"`
	MaxNotional   float64                `protobuf:"fixed64,3,opt,name=max_notional,json=maxNotional,proto3" json:"max_notional,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskLimit) Reset() {
	*x = RiskLimit{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskLimit) ProtoMessage() {}

func (x *RiskLimit) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskLimit.ProtoReflect.Descriptor instead.
func (*RiskLimit) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *RiskLimit) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *RiskLimit) GetMaxPosition() int32 {
	if x != nil {
		return x.MaxPosition
	}
	return 0
}

func (x *RiskLimit) GetMaxNotional() float64 {
	if x != nil {
		return x.MaxNotional
	}
	return 0
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         AlertLevel             `protobuf:"varint,1,opt,name=level,proto3,enum=ib.platform.v1.AlertLevel" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *Alert) GetLevel() AlertLevel {
	if x != nil {
		return x.Level
	}
	return AlertLevel_ALERT_LEVEL_UNSPECIFIED
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Metrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NetLiq            float64                `protobuf:"fixed64,1,opt,name=net_liq,json=netLiq,proto3" json:"net_liq,omitempty"`
	BuyingPower       float64                `protobuf:"fixed64,2,opt,name=buying_power,json=buyingPower,proto3" json:"buying_power,omitempty"`
	ExcessLiquidity   float64                `protobuf:"fixed64,3,opt,name=excess_liquidity,json=excessLiquidity,proto3" json:"excess_liquidity,omitempty"`
	MarginRequirement float64                `protobuf:"fixed64,4,opt,name=margin_requirement,json=marginRequirement,proto3" json:"margin_requirement,omitempty"`
	Commissions       float64                `protobuf:"fixed64,5,opt,name=commissions,proto3" json:"commissions,omitempty"`
	PortalOk          bool                   `protobuf:"varint,6,opt,name=portal_ok,json=portalOk,proto3" json:"portal_ok,omitempty"`
	TwsOk             bool                   `protobuf:"varint,7,opt,name=tws_ok,json=twsOk,proto3" json:"tws_ok,omitempty"`
	OratsOk           bool                   `protobuf:"varint,8,opt,name=orats_ok,json=oratsOk,proto3" json:"orats_ok,omitempty"`
	QuestdbOk         bool                   `protobuf:"varint,9,opt,name=questdb_ok,json=questdbOk,proto3" json:"questdb_ok,omitempty"`
	NatsOk            bool                   `protobuf:"varint,10,opt,name=nats_ok,json=natsOk,proto3" json:"nats_ok,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Metrics) GetNetLiq() float64 {
	if x != nil {
		return x.NetLiq
	}
	return 0
}

func (x *Metrics) GetBuyingPower() float64 {
	if x != nil {
		return x.BuyingPower
	}
	return 0
}

func (x *Metrics) GetExcessLiquidity() float64 {
	if x != nil {
		return x.ExcessLiquidity
	}
	return 0
}

func (x *Metrics) GetMarginRequirement() float64 {
	if x != nil {
		return x.MarginRequirement
	}
	return 0
}

func (x *Metrics) GetCommissions() float64 {
	if x != nil {
		return x.Commissions
	}
	return 0
}

func (x *Metrics) GetPortalOk() bool {
	if x != nil {
		return x.PortalOk
	}
	return false
}

func (x *Metrics) GetTwsOk() bool {
	if x != nil {
		return x.TwsOk
	}
	return false
}

func (x *Metrics) GetOratsOk() bool {
	if x != nil {
		return x.OratsOk
	}
	return false
}

func (x *Metrics) GetQuestdbOk() bool {
	if x != nil {
		return x.QuestdbOk
	}
	return false
}

func (x *Metrics) GetNatsOk() bool {
	if x != nil {
		return x.NatsOk
	}
	return false
}

type SystemSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GeneratedAt   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=generated_at,json=generatedAt,proto3" json:"generated_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Strategy      string                 `protobuf:"bytes,4,opt,name=strategy,proto3" json:"strategy,omitempty"`
	AccountId     string                 `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Metrics       *Metrics               `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Symbols       []*SymbolSnapshot      `protobuf:"bytes,7,rep,name=symbols,proto3" json:"symbols,omitempty"`
	Positions     []*Position            `protobuf:"bytes,8,rep,name=positions,proto3" json:"positions,omitempty"`
	Historic      []*HistoricPosition    `protobuf:"bytes,9,rep,name=historic,proto3" json:"historic,omitempty"`
	Orders        []*Order               `protobuf:"bytes,10,rep,name=orders,proto3" json:"orders,omitempty"`
	Decisions     []*StrategyDecision    `protobuf:"bytes,11,rep,name=decisions,proto3" json:"decisions,omitempty"`
	Alerts        []*Alert               `protobuf:"bytes,12,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Risk          *RiskStatus            `protobuf:"bytes,13,opt,name=risk,proto3" json:"risk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemSnapshot) Reset() {
	*x = SystemSnapshot{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemSnapshot) ProtoMessage() {}

func (x *SystemSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemSnapshot.ProtoReflect.Descriptor instead.
func (*SystemSnapshot) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *SystemSnapshot) GetGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GeneratedAt
	}
	return nil
}

func (x *SystemSnapshot) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SystemSnapshot) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SystemSnapshot) GetStrategy() string {
	if x != nil {
		return x.Strategy
	}
	return ""
}

func (x *SystemSnapshot) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SystemSnapshot) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *SystemSnapshot) GetSymbols() []*SymbolSnapshot {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *SystemSnapshot) GetPositions() []*Position {
	if x != nil {
		return x.Positions
	}
	return nil
}

func (x *SystemSnapshot) GetHistoric() []*HistoricPosition {
	if x != nil {
		return x.Historic
	}
	return nil
}

func (x *SystemSnapshot) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *SystemSnapshot) GetDecisions() []*StrategyDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *SystemSnapshot) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *SystemSnapshot) GetRisk() *RiskStatus {
	if x != nil {
		return x.Risk
	}
	return nil
}

type NatsEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	MessageType   string                 `protobuf:"bytes,4,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NatsEnvelope) Reset() {
	*x = NatsEnvelope{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NatsEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NatsEnvelope) ProtoMessage() {}

func (x *NatsEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NatsEnvelope.ProtoReflect.Descriptor instead.
func (*NatsEnvelope) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

func (x *NatsEnvelope) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NatsEnvelope) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *NatsEnvelope) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *NatsEnvelope) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *NatsEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type OptionContract struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Expiry        string                 `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Strike        float64                `protobuf:"fixed64,3,opt,name=strike,proto3" json:"strike,omitempty"`
	OptionType    OptionTypeEnum         `protobuf:"varint,4,opt,name=option_type,json=optionType,proto3,enum=ib.platform.v1.OptionTypeEnum" json:"option_type,omitempty"`
	Exchange      string                 `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	LocalSymbol   string                 `protobuf:"bytes,6,opt,name=local_symbol,json=localSymbol,proto3" json:"local_symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionContract) Reset() {
	*x = OptionContract{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionContract) ProtoMessage() {}

func (x *OptionContract) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionContract.ProtoReflect.Descriptor instead.
func (*OptionContract) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

func (x *OptionContract) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *OptionContract) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *OptionContract) GetStrike() float64 {
	if x != nil {
		return x.Strike
	}
	return 0
}

func (x *OptionContract) GetOptionType() OptionTypeEnum {
	if x != nil {
		return x.OptionType
	}
	return OptionTypeEnum_OPTION_TYPE_UNSPECIFIED
}

func (x *OptionContract) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *OptionContract) GetLocalSymbol() string {
	if x != nil {
		return x.LocalSymbol
	}
	return ""
}

type BoxSpreadLeg struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	LongCall               *OptionContract        `protobuf:"bytes,1,opt,name=long_call,json=longCall,proto3" json:"long_call,omitempty"`
	ShortCall              *OptionContract        `protobuf:"bytes,2,opt,name=short_call,json=shortCall,proto3" json:"short_call,omitempty"`
	LongPut                *OptionContract        `protobuf:"bytes,3,opt,name=long_put,json=longPut,proto3" json:"long_put,omitempty"`
	ShortPut               *OptionContract        `protobuf:"bytes,4,opt,name=short_put,json=shortPut,proto3" json:"short_put,omitempty"`
	NetDebit               float64                `protobuf:"fixed64,5,opt,name=net_debit,json=netDebit,proto3" json:"net_debit,omitempty"`
	TheoreticalValue       float64                `protobuf:"fixed64,6,opt,name=theoretical_value,json=theoreticalValue,proto3" json:"theoretical_value,omitempty"`
	ArbitrageProfit        float64                `protobuf:"fixed64,7,opt,name=arbitrage_profit,json=arbitrageProfit,proto3" json:"arbitrage_profit,omitempty"`
	RoiPercent             float64                `protobuf:"fixed64,8,opt,name=roi_percent,json=roiPercent,proto3" json:"roi_percent,omitempty"`
	LongCallPrice          float64                `protobuf:"fixed64,9,opt,name=long_call_price,json=longCallPrice,proto3" json:"long_call_price,omitempty"`
	ShortCallPrice         float64                `protobuf:"fixed64,10,opt,name=short_call_price,json=shortCallPrice,proto3" json:"short_call_price,omitempty"`
	LongPutPrice           float64                `protobuf:"fixed64,11,opt,name=long_put_price,json=longPutPrice,proto3" json:"long_put_price,omitempty"`
	ShortPutPrice          float64                `protobuf:"fixed64,12,opt,name=short_put_price,json=shortPutPrice,proto3" json:"short_put_price,omitempty"`
	LongCallBidAskSpread   float64                `protobuf:"fixed64,13,opt,name=long_call_bid_ask_spread,json=longCallBidAskSpread,proto3" json:"long_call_bid_ask_spread,omitempty"`
	ShortCallBidAskSpread  float64                `protobuf:"fixed64,14,opt,name=short_call_bid_ask_spread,json=shortCallBidAskSpread,proto3" json:"short_call_bid_ask_spread,omitempty"`
	LongPutBidAskSpread    float64                `protobuf:"fixed64,15,opt,name=long_put_bid_ask_spread,json=longPutBidAskSpread,proto3" json:"long_put_bid_ask_spread,omitempty"`
	ShortPutBidAskSpread   float64                `protobuf:"fixed64,16,opt,name=short_put_bid_ask_spread,json=shortPutBidAskSpread,proto3" json:"short_put_bid_ask_spread,omitempty"`
	BuyNetDebit            float64                `protobuf:"fixed64,17,opt,name=buy_net_debit,json=buyNetDebit,proto3" json:"buy_net_debit,omitempty"`
	BuyProfit              float64                `protobuf:"fixed64,18,opt,name=buy_profit,json=buyProfit,proto3" json:"buy_profit,omitempty"`
	BuyImpliedRate         float64                `protobuf:"fixed64,19,opt,name=buy_implied_rate,json=buyImpliedRate,proto3" json:"buy_implied_rate,omitempty"`
	SellNetCredit          float64                `protobuf:"fixed64,20,opt,name=sell_net_credit,json=sellNetCredit,proto3" json:"sell_net_credit,omitempty"`
	SellProfit             float64                `protobuf:"fixed64,21,opt,name=sell_profit,json=sellProfit,proto3" json:"sell_profit,omitempty"`
	SellImpliedRate        float64                `protobuf:"fixed64,22,opt,name=sell_implied_rate,json=sellImpliedRate,proto3" json:"sell_implied_rate,omitempty"`
	BuySellDisparity       float64                `protobuf:"fixed64,23,opt,name=buy_sell_disparity,json=buySellDisparity,proto3" json:"buy_sell_disparity,omitempty"`
	PutCallParityViolation float64                `protobuf:"fixed64,24,opt,name=put_call_parity_violation,json=putCallParityViolation,proto3" json:"put_call_parity_violation,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BoxSpreadLeg) Reset() {
	*x = BoxSpreadLeg{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxSpreadLeg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxSpreadLeg) ProtoMessage() {}

func (x *BoxSpreadLeg) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxSpreadLeg.ProtoReflect.Descriptor instead.
func (*BoxSpreadLeg) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *BoxSpreadLeg) GetLongCall() *OptionContract {
	if x != nil {
		return x.LongCall
	}
	return nil
}

func (x *BoxSpreadLeg) GetShortCall() *OptionContract {
	if x != nil {
		return x.ShortCall
	}
	return nil
}

func (x *BoxSpreadLeg) GetLongPut() *OptionContract {
	if x != nil {
		return x.LongPut
	}
	return nil
}

func (x *BoxSpreadLeg) GetShortPut() *OptionContract {
	if x != nil {
		return x.ShortPut
	}
	return nil
}

func (x *BoxSpreadLeg) GetNetDebit() float64 {
	if x != nil {
		return x.NetDebit
	}
	return 0
}

func (x *BoxSpreadLeg) GetTheoreticalValue() float64 {
	if x != nil {
		return x.TheoreticalValue
	}
	return 0
}

func (x *BoxSpreadLeg) GetArbitrageProfit() float64 {
	if x != nil {
		return x.ArbitrageProfit
	}
	return 0
}

func (x *BoxSpreadLeg) GetRoiPercent() float64 {
	if x != nil {
		return x.RoiPercent
	}
	return 0
}

func (x *BoxSpreadLeg) GetLongCallPrice() float64 {
	if x != nil {
		return x.LongCallPrice
	}
	return 0
}

func (x *BoxSpreadLeg) GetShortCallPrice() float64 {
	if x != nil {
		return x.ShortCallPrice
	}
	return 0
}

func (x *BoxSpreadLeg) GetLongPutPrice() float64 {
	if x != nil {
		return x.LongPutPrice
	}
	return 0
}

func (x *BoxSpreadLeg) GetShortPutPrice() float64 {
	if x != nil {
		return x.ShortPutPrice
	}
	return 0
}

func (x *BoxSpreadLeg) GetLongCallBidAskSpread() float64 {
	if x != nil {
		return x.LongCallBidAskSpread
	}
	return 0
}

func (x *BoxSpreadLeg) GetShortCallBidAskSpread() float64 {
	if x != nil {
		return x.ShortCallBidAskSpread
	}
	return 0
}

func (x *BoxSpreadLeg) GetLongPutBidAskSpread() float64 {
	if x != nil {
		return x.LongPutBidAskSpread
	}
	return 0
}

func (x *BoxSpreadLeg) GetShortPutBidAskSpread() float64 {
	if x != nil {
		return x.ShortPutBidAskSpread
	}
	return 0
}

func (x *BoxSpreadLeg) GetBuyNetDebit() float64 {
	if x != nil {
		return x.BuyNetDebit
	}
	return 0
}

func (x *BoxSpreadLeg) GetBuyProfit() float64 {
	if x != nil {
		return x.BuyProfit
	}
	return 0
}

func (x *BoxSpreadLeg) GetBuyImpliedRate() float64 {
	if x != nil {
		return x.BuyImpliedRate
	}
	return 0
}

func (x *BoxSpreadLeg) GetSellNetCredit() float64 {
	if x != nil {
		return x.SellNetCredit
	}
	return 0
}

func (x *BoxSpreadLeg) GetSellProfit() float64 {
	if x != nil {
		return x.SellProfit
	}
	return 0
}

func (x *BoxSpreadLeg) GetSellImpliedRate() float64 {
	if x != nil {
		return x.SellImpliedRate
	}
	return 0
}

func (x *BoxSpreadLeg) GetBuySellDisparity() float64 {
	if x != nil {
		return x.BuySellDisparity
	}
	return 0
}

func (x *BoxSpreadLeg) GetPutCallParityViolation() float64 {
	if x != nil {
		return x.PutCallParityViolation
	}
	return 0
}

type BoxSpreadScenario struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	StrikeWidth       float64                `protobuf:"fixed64,2,opt,name=strike_width,json=strikeWidth,proto3" json:"strike_width,omitempty"`
	TheoreticalValue  float64                `protobuf:"fixed64,3,opt,name=theoretical_value,json=theoreticalValue,proto3" json:"theoretical_value,omitempty"`
	EstimatedNetDebit float64                `protobuf:"fixed64,4,opt,name=estimated_net_debit,json=estimatedNetDebit,proto3" json:"estimated_net_debit,omitempty"`
	ImpliedApr        float64                `protobuf:"fixed64,5,opt,name=implied_apr,json=impliedApr,proto3" json:"implied_apr,omitempty"`
	ScenarioType      string                 `protobuf:"bytes,6,opt,name=scenario_type,json=scenarioType,proto3" json:"scenario_type,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BoxSpreadScenario) Reset() {
	*x = BoxSpreadScenario{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxSpreadScenario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxSpreadScenario) ProtoMessage() {}

func (x *BoxSpreadScenario) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxSpreadScenario.ProtoReflect.Descriptor instead.
func (*BoxSpreadScenario) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *BoxSpreadScenario) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BoxSpreadScenario) GetStrikeWidth() float64 {
	if x != nil {
		return x.StrikeWidth
	}
	return 0
}

func (x *BoxSpreadScenario) GetTheoreticalValue() float64 {
	if x != nil {
		return x.TheoreticalValue
	}
	return 0
}

func (x *BoxSpreadScenario) GetEstimatedNetDebit() float64 {
	if x != nil {
		return x.EstimatedNetDebit
	}
	return 0
}

func (x *BoxSpreadScenario) GetImpliedApr() float64 {
	if x != nil {
		return x.ImpliedApr
	}
	return 0
}

func (x *BoxSpreadScenario) GetScenarioType() string {
	if x != nil {
		return x.ScenarioType
	}
	return ""
}

type BoxSpreadExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	LowerStrike   int32                  `protobuf:"varint,2,opt,name=lower_strike,json=lowerStrike,proto3" json:"lower_strike,omitempty"`
	UpperStrike   int32                  `protobuf:"varint,3,opt,name=upper_strike,json=upperStrike,proto3" json:"upper_strike,omitempty"`
	Expiry        string                 `protobuf:"bytes,4,opt,name=expiry,proto3" json:"expiry,omitempty"`
	NetDebit      float64                `protobuf:"fixed64,5,opt,name=net_debit,json=netDebit,proto3" json:"net_debit,omitempty"`
	TradeId       string                 `protobuf:"bytes,6,opt,name=trade_id,json=tradeId,proto3" json:"trade_id,omitempty"`
	ExecutedAt    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoxSpreadExecution) Reset() {
	*x = BoxSpreadExecution{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoxSpreadExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxSpreadExecution) ProtoMessage() {}

func (x *BoxSpreadExecution) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxSpreadExecution.ProtoReflect.Descriptor instead.
func (*BoxSpreadExecution) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

func (x *BoxSpreadExecution) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BoxSpreadExecution) GetLowerStrike() int32 {
	if x != nil {
		return x.LowerStrike
	}
	return 0
}

func (x *BoxSpreadExecution) GetUpperStrike() int32 {
	if x != nil {
		return x.UpperStrike
	}
	return 0
}

func (x *BoxSpreadExecution) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *BoxSpreadExecution) GetNetDebit() float64 {
	if x != nil {
		return x.NetDebit
	}
	return 0
}

func (x *BoxSpreadExecution) GetTradeId() string {
	if x != nil {
		return x.TradeId
	}
	return ""
}

func (x *BoxSpreadExecution) GetExecutedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExecutedAt
	}
	return nil
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\x0eib.platform.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb3\x01\n" +
	"\x0fMarketDataEvent\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x03 \x01(\x01R\x03ask\x12\x12\n" +
	"\x04last\x18\x04 \x01(\x01R\x04last\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x04R\x06volume\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc4\x01\n" +
	"\x0eCandleSnapshot\x12\x12\n" +
	"\x04open\x18\x01 \x01(\x01R\x04open\x12\x12\n" +
	"\x04high\x18\x02 \x01(\x01R\x04high\x12\x10\n" +
	"\x03low\x18\x03 \x01(\x01R\x03low\x12\x14\n" +
	"\x05close\x18\x04 \x01(\x01R\x05close\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x04R\x06volume\x12\x14\n" +
	"\x05entry\x18\x06 \x01(\x01R\x05entry\x124\n" +
	"\aupdated\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\aupdated\"\x9c\x02\n" +
	"\x0eSymbolSnapshot\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04last\x18\x02 \x01(\x01R\x04last\x12\x10\n" +
	"\x03bid\x18\x03 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\x04 \x01(\x01R\x03ask\x12\x16\n" +
	"\x06spread\x18\x05 \x01(\x01R\x06spread\x12\x10\n" +
	"\x03roi\x18\x06 \x01(\x01R\x03roi\x12\x1f\n" +
	"\vmaker_count\x18\a \x01(\rR\n" +
	"makerCount\x12\x1f\n" +
	"\vtaker_count\x18\b \x01(\rR\n" +
	"takerCount\x12\x16\n" +
	"\x06volume\x18\t \x01(\x04R\x06volume\x126\n" +
	"\x06candle\x18\n" +
	" \x01(\v2\x1e.ib.platform.v1.CandleSnapshotR\x06candle\"\xa8\x01\n" +
	"\bPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"cost_basis\x18\x04 \x01(\x01R\tcostBasis\x12\x12\n" +
	"\x04mark\x18\x05 \x01(\x01R\x04mark\x12%\n" +
	"\x0eunrealized_pnl\x18\x06 \x01(\x01R\runrealizedPnl\"\xb2\x01\n" +
	"\x10HistoricPosition\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12!\n" +
	"\frealized_pnl\x18\x04 \x01(\x01R\vrealizedPnl\x127\n" +
	"\tclosed_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\"\xb6\x01\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12=\n" +
	"\fsubmitted_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vsubmittedAt\"\xa9\x01\n" +
	"\x10StrategyDecision\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x12\n" +
	"\x04side\x18\x03 \x01(\tR\x04side\x12\x12\n" +
	"\x04mark\x18\x04 \x01(\x01R\x04mark\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"x\n" +
	"\x0eStrategySignal\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"y\n" +
	"\n" +
	"RiskStatus\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"i\n" +
	"\tRiskLimit\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\fmax_position\x18\x02 \x01(\x05R\vmaxPosition\x12!\n" +
	"\fmax_notional\x18\x03 \x01(\x01R\vmaxNotional\"\x8d\x01\n" +
	"\x05Alert\x120\n" +
	"\x05level\x18\x01 \x01(\x0e2\x1a.ib.platform.v1.AlertLevelR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"\xc8\x02\n" +
	"\aMetrics\x12\x17\n" +
	"\anet_liq\x18\x01 \x01(\x01R\x06netLiq\x12!\n" +
	"\fbuying_power\x18\x02 \x01(\x01R\vbuyingPower\x12)\n" +
	"\x10excess_liquidity\x18\x03 \x01(\x01R\x0fexcessLiquidity\x12-\n" +
	"\x12margin_requirement\x18\x04 \x01(\x01R\x11marginRequirement\x12 \n" +
	"\vcommissions\x18\x05 \x01(\x01R\vcommissions\x12\x1b\n" +
	"\tportal_ok\x18\x06 \x01(\bR\bportalOk\x12\x15\n" +
	"\x06tws_ok\x18\a \x01(\bR\x05twsOk\x12\x19\n" +
	"\borats_ok\x18\b \x01(\bR\aoratsOk\x12\x1d\n" +
	"\n" +
	"questdb_ok\x18\t \x01(\bR\tquestdbOk\x12\x17\n" +
	"\anats_ok\x18\n" +
	" \x01(\bR\x06natsOk\"\x8a\x05\n" +
	"\x0eSystemSnapshot\x12=\n" +
	"\fgenerated_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vgeneratedAt\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12\x1a\n" +
	"\bstrategy\x18\x04 \x01(\tR\bstrategy\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\x121\n" +
	"\ametrics\x18\x06 \x01(\v2\x17.ib.platform.v1.MetricsR\ametrics\x128\n" +
	"\asymbols\x18\a \x03(\v2\x1e.ib.platform.v1.SymbolSnapshotR\asymbols\x126\n" +
	"\tpositions\x18\b \x03(\v2\x18.ib.platform.v1.PositionR\tpositions\x12<\n" +
	"\bhistoric\x18\t \x03(\v2 .ib.platform.v1.HistoricPositionR\bhistoric\x12-\n" +
	"\x06orders\x18\n" +
	" \x03(\v2\x15.ib.platform.v1.OrderR\x06orders\x12>\n" +
	"\tdecisions\x18\v \x03(\v2 .ib.platform.v1.StrategyDecisionR\tdecisions\x12-\n" +
	"\x06alerts\x18\f \x03(\v2\x15.ib.platform.v1.AlertR\x06alerts\x12.\n" +
	"\x04risk\x18\r \x01(\v2\x1a.ib.platform.v1.RiskStatusR\x04risk\"\xad\x01\n" +
	"\fNatsEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12!\n" +
	"\fmessage_type\x18\x04 \x01(\tR\vmessageType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\"\xd8\x01\n" +
	"\x0eOptionContract\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\tR\x06expiry\x12\x16\n" +
	"\x06strike\x18\x03 \x01(\x01R\x06strike\x12?\n" +
	"\voption_type\x18\x04 \x01(\x0e2\x1e.ib.platform.v1.OptionTypeEnumR\n" +
	"optionType\x12\x1a\n" +
	"\bexchange\x18\x05 \x01(\tR\bexchange\x12!\n" +
	"\flocal_symbol\x18\x06 \x01(\tR\vlocalSymbol\"\xe3\b\n" +
	"\fBoxSpreadLeg\x12;\n" +
	"\tlong_call\x18\x01 \x01(\v2\x1e.ib.platform.v1.OptionContractR\blongCall\x12=\n" +
	"\n" +
	"short_call\x18\x02 \x01(\v2\x1e.ib.platform.v1.OptionContractR\tshortCall\x129\n" +
	"\blong_put\x18\x03 \x01(\v2\x1e.ib.platform.v1.OptionContractR\alongPut\x12;\n" +
	"\tshort_put\x18\x04 \x01(\v2\x1e.ib.platform.v1.OptionContractR\bshortPut\x12\x1b\n" +
	"\tnet_debit\x18\x05 \x01(\x01R\bnetDebit\x12+\n" +
	"\x11theoretical_value\x18\x06 \x01(\x01R\x10theoreticalValue\x12)\n" +
	"\x10arbitrage_profit\x18\a \x01(\x01R\x0farbitrageProfit\x12\x1f\n" +
	"\vroi_percent\x18\b \x01(\x01R\n" +
	"roiPercent\x12&\n" +
	"\x0flong_call_price\x18\t \x01(\x01R\rlongCallPrice\x12(\n" +
	"\x10short_call_price\x18\n" +
	" \x01(\x01R\x0eshortCallPrice\x12$\n" +
	"\x0elong_put_price\x18\v \x01(\x01R\flongPutPrice\x12&\n" +
	"\x0fshort_put_price\x18\f \x01(\x01R\rshortPutPrice\x126\n" +
	"\x18long_call_bid_ask_spread\x18\r \x01(\x01R\x14longCallBidAskSpread\x128\n" +
	"\x19short_call_bid_ask_spread\x18\x0e \x01(\x01R\x15shortCallBidAskSpread\x124\n" +
	"\x17long_put_bid_ask_spread\x18\x0f \x01(\x01R\x13longPutBidAskSpread\x126\n" +
	"\x18short_put_bid_ask_spread\x18\x10 \x01(\x01R\x14shortPutBidAskSpread\x12\"\n" +
	"\rbuy_net_debit\x18\x11 \x01(\x01R\vbuyNetDebit\x12\x1d\n" +
	"\n" +
	"buy_profit\x18\x12 \x01(\x01R\tbuyProfit\x12(\n" +
	"\x10buy_implied_rate\x18\x13 \x01(\x01R\x0ebuyImpliedRate\x12&\n" +
	"\x0fsell_net_credit\x18\x14 \x01(\x01R\rsellNetCredit\x12\x1f\n" +
	"\vsell_profit\x18\x15 \x01(\x01R\n" +
	"sellProfit\x12*\n" +
	"\x11sell_implied_rate\x18\x16 \x01(\x01R\x0fsellImpliedRate\x12,\n" +
	"\x12buy_sell_disparity\x18\x17 \x01(\x01R\x10buySellDisparity\x129\n" +
	"\x19put_call_parity_violation\x18\x18 \x01(\x01R\x16putCallParityViolation\"\xf1\x01\n" +
	"\x11BoxSpreadScenario\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\fstrike_width\x18\x02 \x01(\x01R\vstrikeWidth\x12+\n" +
	"\x11theoretical_value\x18\x03 \x01(\x01R\x10theoreticalValue\x12.\n" +
	"\x13estimated_net_debit\x18\x04 \x01(\x01R\x11estimatedNetDebit\x12\x1f\n" +
	"\vimplied_apr\x18\x05 \x01(\x01R\n" +
	"impliedApr\x12#\n" +
	"\rscenario_type\x18\x06 \x01(\tR\fscenarioType\"\xff\x01\n" +
	"\x12BoxSpreadExecution\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12!\n" +
	"\flower_strike\x18\x02 \x01(\x05R\vlowerStrike\x12!\n" +
	"\fupper_strike\x18\x03 \x01(\x05R\vupperStrike\x12\x16\n" +
	"\x06expiry\x18\x04 \x01(\tR\x06expiry\x12\x1b\n" +
	"\tnet_debit\x18\x05 \x01(\x01R\bnetDebit\x12\x19\n" +
	"\btrade_id\x18\x06 \x01(\tR\atradeId\x12;\n" +
	"\vexecuted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"executedAt*o\n" +
	"\n" +
	"AlertLevel\x12\x1b\n" +
	"\x17ALERT_LEVEL_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ALERT_LEVEL_INFO\x10\x01\x12\x17\n" +
	"\x13ALERT_LEVEL_WARNING\x10\x02\x12\x15\n" +
	"\x11ALERT_LEVEL_ERROR\x10\x03*X\n" +
	"\x0eOptionTypeEnum\x12\x1b\n" +
	"\x17OPTION_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10OPTION_TYPE_CALL\x10\x01\x12\x13\n" +
	"\x0fOPTION_TYPE_PUT\x10\x02B-Z+github.com/dlowes/ib-platform/proto/v1;pbv1b\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_messages_proto_goTypes = []any{
	(AlertLevel)(0),               // 0: ib.platform.v1.AlertLevel
	(OptionTypeEnum)(0),           // 1: ib.platform.v1.OptionTypeEnum
	(*MarketDataEvent)(nil),       // 2: ib.platform.v1.MarketDataEvent
	(*CandleSnapshot)(nil),        // 3: ib.platform.v1.CandleSnapshot
	(*SymbolSnapshot)(nil),        // 4: ib.platform.v1.SymbolSnapshot
	(*Position)(nil),              // 5: ib.platform.v1.Position
	(*HistoricPosition)(nil),      // 6: ib.platform.v1.HistoricPosition
	(*Order)(nil),                 // 7: ib.platform.v1.Order
	(*StrategyDecision)(nil),      // 8: ib.platform.v1.StrategyDecision
	(*StrategySignal)(nil),        // 9: ib.platform.v1.StrategySignal
	(*RiskStatus)(nil),            // 10: ib.platform.v1.RiskStatus
	(*RiskLimit)(nil),             // 11: ib.platform.v1.RiskLimit
	(*Alert)(nil),                 // 12: ib.platform.v1.Alert
	(*Metrics)(nil),               // 13: ib.platform.v1.Metrics
	(*SystemSnapshot)(nil),        // 14: ib.platform.v1.SystemSnapshot
	(*NatsEnvelope)(nil),          // 15: ib.platform.v1.NatsEnvelope
	(*OptionContract)(nil),        // 16: ib.platform.v1.OptionContract
	(*BoxSpreadLeg)(nil),          // 17: ib.platform.v1.BoxSpreadLeg
	(*BoxSpreadScenario)(nil),     // 18: ib.platform.v1.BoxSpreadScenario
	(*BoxSpreadExecution)(nil),    // 19: ib.platform.v1.BoxSpreadExecution
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_messages_proto_depIdxs = []int32{
	20, // 0: ib.platform.v1.MarketDataEvent.timestamp:type_name -> google.protobuf.Timestamp
	20, // 1: ib.platform.v1.CandleSnapshot.updated:type_name -> google.protobuf.Timestamp
	3,  // 2: ib.platform.v1.SymbolSnapshot.candle:type_name -> ib.platform.v1.CandleSnapshot
	20, // 3: ib.platform.v1.HistoricPosition.closed_at:type_name -> google.protobuf.Timestamp
	20, // 4: ib.platform.v1.Order.submitted_at:type_name -> google.protobuf.Timestamp
	20, // 5: ib.platform.v1.StrategyDecision.created_at:type_name -> google.protobuf.Timestamp
	20, // 6: ib.platform.v1.StrategySignal.timestamp:type_name -> google.protobuf.Timestamp
	20, // 7: ib.platform.v1.RiskStatus.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 8: ib.platform.v1.Alert.level:type_name -> ib.platform.v1.AlertLevel
	20, // 9: ib.platform.v1.Alert.timestamp:type_name -> google.protobuf.Timestamp
	20, // 10: ib.platform.v1.SystemSnapshot.generated_at:type_name -> google.protobuf.Timestamp
	20, // 11: ib.platform.v1.SystemSnapshot.started_at:type_name -> google.protobuf.Timestamp
	13, // 12: ib.platform.v1.SystemSnapshot.metrics:type_name -> ib.platform.v1.Metrics
	4,  // 13: ib.platform.v1.SystemSnapshot.symbols:type_name -> ib.platform.v1.SymbolSnapshot
	5,  // 14: ib.platform.v1.SystemSnapshot.positions:type_name -> ib.platform.v1.Position
	6,  // 15: ib.platform.v1.SystemSnapshot.historic:type_name -> ib.platform.v1.HistoricPosition
	7,  // 16: ib.platform.v1.SystemSnapshot.orders:type_name -> ib.platform.v1.Order
	8,  // 17: ib.platform.v1.SystemSnapshot.decisions:type_name -> ib.platform.v1.StrategyDecision
	12, // 18: ib.platform.v1.SystemSnapshot.alerts:type_name -> ib.platform.v1.Alert
	10, // 19: ib.platform.v1.SystemSnapshot.risk:type_name -> ib.platform.v1.RiskStatus
	20, // 20: ib.platform.v1.NatsEnvelope.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 21: ib.platform.v1.OptionContract.option_type:type_name -> ib.platform.v1.OptionTypeEnum
	16, // 22: ib.platform.v1.BoxSpreadLeg.long_call:type_name -> ib.platform.v1.OptionContract
	16, // 23: ib.platform.v1.BoxSpreadLeg.short_call:type_name -> ib.platform.v1.OptionContract
	16, // 24: ib.platform.v1.BoxSpreadLeg.long_put:type_name -> ib.platform.v1.OptionContract
	16, // 25: ib.platform.v1.BoxSpreadLeg.short_put:type_name -> ib.platform.v1.OptionContract
	20, // 26: ib.platform.v1.BoxSpreadExecution.executed_at:type_name -> google.protobuf.Timestamp
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
