# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Documentation: https://docs.brew.sh/Formula-Cookbook
#                https://rubydoc.brew.sh/Formula
# PLEASE REMOVE ALL GENERATED COMMENTS WHEN SUBMITTING YOUR PULL REQUEST!

class IbBoxSpreadTui < Formula
  desc "Terminal User Interface for Synthetic Financing Platform (Python)"
  homepage "https://github.com/davidl71/synthetic-financing-platform"
  # For private repositories, use GitDownloadStrategy with SSH URL
  # This allows Homebrew to clone the repo and checkout the tag
  url "git@github.com:davidl71/synthetic-financing-platform.git", tag: "v1.0.0", using: :git
  license "MIT"
  head "git@github.com:davidl71/synthetic-financing-platform.git", branch: "main", using: :git

  depends_on "python@3.11"

  def install
    # Install Python TUI dependencies
    system "python3", "-m", "pip", "install", "--prefix=#{prefix}", "textual>=0.40.0", "requests>=2.31.0"

    # Create wrapper script
    (bin/"ib-box-spread-tui").write <<~EOS
      #!/bin/bash
      exec python3 -m python.tui "$@"
    EOS
    chmod 0755, bin/"ib-box-spread-tui"
  end

  test do
    # Test that script exists and Python module can be imported
    assert_predicate bin/"ib-box-spread-tui", :exist?
    system "python3", "-c", "import python.tui" rescue nil
  end
end
